name: tasks
on:
  push:
    branches:
      - dist
jobs: 
  prepare:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.POD_DATA_GEN }}'
      - name: prep
        run: |
          mkdir tmp
          git add tmp
          git commit -m "Create tmp folder"
          git push origin dist
